apiVersion: v2
name: odoopack
description: Odoo addon package registry with web API, background worker and frontend
type: application
version: 0.1.1
appVersion: "0.1.0"
home: https://github.com/wimwenigerkind/odoopack-registry
sources:
  - https://github.com/wimwenigerkind/odoopack-registry
keywords:
  - odoo
  - registry
  - packages
  - addons
maintainers:
  - name: Wim Wenigerkind
    email: info@wimwenigerkind.com
    url: https://wimwenigerkind.com
