{{- if .Values.ingress.enabled }}
{{- $fullName := include "odoopack.fullname" . }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "odoopack.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- range .Values.ingress.backendPaths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-web
                port:
                  number: {{ $.Values.web.service.port }}
          {{- end }}
          {{- if .Values.frontend.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
          {{- end }}
{{- end }}
